### ISSUE TITLE
Initial organization structure governance

### ISSUE THREAD

**Issue by sciwhiz12** [neoforged/governance#2]
As with any organization, NeoForged[^name] needs an organizational structure and governance.

While we could operate on an informal structure and governance agreed to by the team in internal discussions, the team believes that it would be much better to codify a clear yet flexible organizational governance, for the benefit of the team (to know who does what, when, and why) and the public (in the interests of transparency).

This (epic) issue tracks the initial creation and implementation of NeoForged's structure and governance.

The initial draft can be viewed on the [`draft/sci/governance` branch](https://github.com/neoforged/governance/tree/draft/sci/governance) on this repository.

**Please discuss the initial governance and structure in the [Goverance thread](https://discord.com/channels/313125603924639766/1130055728254693376) on the Discord server. Thank you.**

### Works in progress

- [ ] Defining the three core bodies
	- [ ] https://github.com/neoforged/governance/issues/3 The Steering Council 
	- [ ] https://github.com/neoforged/governance/issues/4 The Moderation team 
	- [ ] https://github.com/neoforged/governance/issues/5 The Maintainers team
- [ ] https://github.com/neoforged/governance/issues/6 Ancillary teams concept
- [ ] Intra-body and inter-body dispute resolution
- [ ] Membership policy
- [ ] Uniform/organization-wide voting policy

[^name]: NeoForge**d** with a `d` refers to the organization, while NeoForge without a `d` refers to the Minecraft modding API project within the organization. This is because the `neoforge` domain and GitHub username were already taken.

**Comment by sciwhiz12** [comment]
Quoting my message in the Governance thread,

> I've been given the revelation that my vision for project governance runs counter to the true vision of the project and its governance, per internal chats (see the private ⁠wisdoms channel, for those with access)
as it seems my vision is without merit, and I do not wish to pursue something which I feel is now doomed to fail (officially or not), I am disengaging from actively working on the project governance moving forward
I've closed the issues I made on the repo, and I've deleted my drafts branch
> 
> I now leave this matter in the hands of all of you, the community, to figure out the project governance in accordance to the vision of the project
